/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceinvadersproject.GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowEvent;

/**
 *
 * @author Karakayn
 */
public class MainMenuFrame extends javax.swing.JFrame {

    private JImagePanel imagePanel;

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
        
        //add the real panel object to our positioning jPanel
        imagePanel = new spaceinvadersproject.GUI.JImagePanel();
        jPanelToReplaceByImageTop.setLayout(new BorderLayout());
        jPanelToReplaceByImageTop.add(imagePanel, BorderLayout.CENTER);
        
        JImagePanel imagePanel2 = new spaceinvadersproject.GUI.JImagePanel();

        jPanelToReplaceByImageBottom.setLayout(new BorderLayout());
        jPanelToReplaceByImageBottom.add(imagePanel2, BorderLayout.CENTER);
        imagePanel.setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStartGame = new javax.swing.JButton();
        jButtonLeave = new javax.swing.JButton();
        jPanelToReplaceByImageTop = new javax.swing.JPanel();
        jPanelToReplaceByImageBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Space Invaders Project");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Space Invader Project"); // NOI18N

        jButtonStartGame.setText("Lancer la partie");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        jButtonLeave.setText("Quitter le jeu");
        jButtonLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveActionPerformed(evt);
            }
        });

        jPanelToReplaceByImageTop.setMinimumSize(new java.awt.Dimension(800, 100));

        javax.swing.GroupLayout jPanelToReplaceByImageTopLayout = new javax.swing.GroupLayout(jPanelToReplaceByImageTop);
        jPanelToReplaceByImageTop.setLayout(jPanelToReplaceByImageTopLayout);
        jPanelToReplaceByImageTopLayout.setHorizontalGroup(
            jPanelToReplaceByImageTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelToReplaceByImageTopLayout.setVerticalGroup(
            jPanelToReplaceByImageTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelToReplaceByImageBottomLayout = new javax.swing.GroupLayout(jPanelToReplaceByImageBottom);
        jPanelToReplaceByImageBottom.setLayout(jPanelToReplaceByImageBottomLayout);
        jPanelToReplaceByImageBottomLayout.setHorizontalGroup(
            jPanelToReplaceByImageBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelToReplaceByImageBottomLayout.setVerticalGroup(
            jPanelToReplaceByImageBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelToReplaceByImageBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelToReplaceByImageTop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLeave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanelToReplaceByImageTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanelToReplaceByImageBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStartGameActionPerformed

    private void jButtonLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_jButtonLeaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLeave;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JPanel jPanelToReplaceByImageBottom;
    private javax.swing.JPanel jPanelToReplaceByImageTop;
    // End of variables declaration//GEN-END:variables
}
